# Generated by Django 5.2.4 on 2025-08-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerseason",
            old_name="position_restriction",
            new_name="position",
        ),
    ]
