# Generated by Django 5.2.4 on 2025-08-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0002_rename_position_restriction_playerseason_position"),
    ]

    operations = [
        migrations.RemoveField(model_name="season", name="crc",),
    ]
