# Generated by Django 5.2.4 on 2025-08-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0003_remove_season_crc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_in_match",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
