# Generated by Django 5.2.4 on 2025-08-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0004_alter_game_game_in_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playoffseries",
            name="match",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="playoff_series",
                to="reference.match",
            ),
        ),
    ]
