# Generated by Django 5.2.4 on 2025-08-08 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0005_alter_playoffseries_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="team1_standing_points",
            field=models.IntegerField(
                blank=True, help_text="Points awarded for standings", null=True
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="team2_standing_points",
            field=models.IntegerField(
                blank=True, help_text="Points awarded for standings", null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerseason",
            name="position",
            field=models.CharField(
                choices=[("O", "Offense"), ("D", "Defense"), ("N", "—")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.IntegerField(blank=True, null=True)),
                ("pops", models.IntegerField(blank=True, null=True)),
                ("grabs", models.IntegerField(blank=True, null=True)),
                ("drops", models.IntegerField(blank=True, null=True)),
                (
                    "hold",
                    models.IntegerField(
                        blank=True, help_text="Hold time in seconds", null=True
                    ),
                ),
                ("captures", models.IntegerField(blank=True, null=True)),
                (
                    "prevent",
                    models.IntegerField(
                        blank=True, help_text="Prevent time in seconds", null=True
                    ),
                ),
                ("returns", models.IntegerField(blank=True, null=True)),
                ("powerups", models.IntegerField(blank=True, null=True)),
                (
                    "player_gamelog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="reference.playergamelog",
                    ),
                ),
            ],
        ),
    ]
