# Generated by Django 5.2.4 on 2025-08-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0006_alter_game_team1_standing_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playergamestats",
            name="time_played",
            field=models.IntegerField(
                blank=True, help_text="Time played in seconds", null=True
            ),
        ),
    ]
