# Generated by Django 5.2.4 on 2025-08-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0007_playerstats_time_played"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="abbr",
            field=models.CharField(
                default="", help_text="Abbreviation for the award name", max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="award",
            name="award_name",
            field=models.CharField(help_text="Full name of the award", max_length=255),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="hold",
            field=models.IntegerField(
                blank=True,
                help_text="Hold time in ticks (1/60th of a second)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="prevent",
            field=models.IntegerField(
                blank=True,
                help_text="Prevent time in ticks (1/60th of a second)",
                null=True,
            ),
        ),
    ]
