# Generated by Django 5.2.4 on 2025-08-12 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0008_award_abbr_alter_award_award_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Full name of the award", max_length=255
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        blank=True,
                        help_text="Abbreviation for the award name",
                        max_length=100,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Link to the award's icon",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="playerseason",
            name="position",
            field=models.CharField(
                choices=[("O", "O"), ("D", "D"), ("N", "—")], default="N", max_length=1
            ),
        ),
        migrations.CreateModel(
            name="AwardReceived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="1 for 1st place, 2 for 2nd, etc.",
                        null=True,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player who won the award",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="reference.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team awarded or player's team",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.teamseason",
                    ),
                ),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference.awardtype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Award",),
    ]
