# Generated by Django 5.2.4 on 2025-08-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference",
            "0009_awardtype_alter_playerseason_position_awardreceived_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="awardtype",
            name="ordering",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="awardtype",
            name="abbr",
            field=models.CharField(
                help_text="Abbreviation for the award name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="awardtype",
            name="name",
            field=models.CharField(help_text="Full name of the award", max_length=255),
        ),
    ]
