# Generated by Django 5.2.4 on 2025-08-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0010_awardtype_ordering_alter_awardtype_abbr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="franchise",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="Link to the franchise's logo image",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="league",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="Link to the league's logo image",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="league",
            name="trophy_icon",
            field=models.CharField(
                blank=True,
                help_text="Link to the league's championship trophy image",
                max_length=100,
                null=True,
            ),
        ),
    ]
