# Generated by Django 5.2.5 on 2025-08-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0012_rename_playerstats_playergamestats_game_paused_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='caps_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='caps_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='caps_off_handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='caps_off_regrab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='flaccids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='good_handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='grabs_off_handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='grabs_off_regrab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='hold_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='kept_flags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='key_returns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='long_holds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='quick_returns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='returns_in_base',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='saves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='total_pups_in_game',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='caps_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='caps_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='caps_off_handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='caps_off_regrab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='flaccids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='good_handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='grabs_off_handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='grabs_off_regrab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='hold_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='kept_flags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='key_returns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='long_holds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='quick_returns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='returns_in_base',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='saves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='total_pups_in_game',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='caps_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='caps_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='caps_off_handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='caps_off_regrab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='flaccids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='good_handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='grabs_off_handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='grabs_off_regrab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='handoffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='hold_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='kept_flags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='key_returns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='long_holds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='quick_returns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='returns_in_base',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='saves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekstats',
            name='total_pups_in_game',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
