# Generated by Django 5.2.4 on 2025-08-23 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0012_game_paused_time_game_resumed_tagpro_eu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerRegulationGameStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_played",
                    models.IntegerField(
                        blank=True,
                        help_text="Time played in ticks (1/60th of a second)",
                        null=True,
                    ),
                ),
                ("tags", models.IntegerField(blank=True, null=True)),
                ("pops", models.IntegerField(blank=True, null=True)),
                ("grabs", models.IntegerField(blank=True, null=True)),
                ("drops", models.IntegerField(blank=True, null=True)),
                (
                    "hold",
                    models.IntegerField(
                        blank=True,
                        help_text="Hold time in ticks (1/60th of a second)",
                        null=True,
                    ),
                ),
                ("captures", models.IntegerField(blank=True, null=True)),
                (
                    "prevent",
                    models.IntegerField(
                        blank=True,
                        help_text="Prevent time in ticks (1/60th of a second)",
                        null=True,
                    ),
                ),
                ("returns", models.IntegerField(blank=True, null=True)),
                ("powerups", models.IntegerField(blank=True, null=True)),
                ("caps_for", models.IntegerField(blank=True, null=True)),
                ("caps_against", models.IntegerField(blank=True, null=True)),
                ("total_pups_in_game", models.IntegerField(blank=True, null=True)),
                ("grabs_off_handoffs", models.IntegerField(blank=True, null=True)),
                ("caps_off_handoffs", models.IntegerField(blank=True, null=True)),
                ("grabs_off_regrab", models.IntegerField(blank=True, null=True)),
                ("caps_off_regrab", models.IntegerField(blank=True, null=True)),
                ("long_holds", models.IntegerField(blank=True, null=True)),
                ("flaccids", models.IntegerField(blank=True, null=True)),
                ("handoffs", models.IntegerField(blank=True, null=True)),
                ("good_handoffs", models.IntegerField(blank=True, null=True)),
                ("quick_returns", models.IntegerField(blank=True, null=True)),
                ("returns_in_base", models.IntegerField(blank=True, null=True)),
                ("saves", models.IntegerField(blank=True, null=True)),
                ("key_returns", models.IntegerField(blank=True, null=True)),
                ("hold_against", models.IntegerField(blank=True, null=True)),
                ("kept_flags", models.IntegerField(blank=True, null=True)),
                (
                    "player_gamelog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulation_stats",
                        to="reference.playergamelog",
                    ),
                ),
            ],
        ),
    ]
