# Generated by Django 5.2.4 on 2025-08-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0013_playergamestats_playerregulationgamestats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerseasonstats",
            name="time_played",
            field=models.IntegerField(
                blank=True,
                help_text="Time played in ticks (1/60th of a second)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerweekstats",
            name="time_played",
            field=models.IntegerField(
                blank=True,
                help_text="Time played in ticks (1/60th of a second)",
                null=True,
            ),
        ),
    ]
