# Generated by Django 5.2.4 on 2025-08-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0014_alter_playerseasonstats_time_played_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="non_regulation",
            field=models.BooleanField(
                default=False,
                help_text="Whether this game is non-regulation and should be excluded from stats (e.g., played on a home map)",
            ),
        ),
        migrations.AlterField(
            model_name="playergamestats",
            name="time_played",
            field=models.IntegerField(
                blank=True,
                help_text="Time played in ticks (1/60th of a second)",
                null=True,
            ),
        ),
    ]
