# Generated by Django 5.2.4 on 2025-08-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0015_game_non_regulation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamseason",
            name="playoff_finish",
            field=models.CharField(
                blank=True,
                help_text="Team's playoff result: '—', 'Missed playoffs', 'Lost [round name]', 'Won [round name]'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teamseason",
            name="seed",
            field=models.IntegerField(
                blank=True,
                help_text="Team's regular season rank based on standing points and tiebreakers",
                null=True,
            ),
        ),
    ]
