# Generated by Django 5.2.4 on 2025-08-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0016_teamseason_playoff_finish_teamseason_seed"),
    ]

    operations = [
        migrations.RemoveField(model_name="playoffseries", name="seed1",),
        migrations.RemoveField(model_name="playoffseries", name="seed2",),
    ]
