# Generated by Django 5.2.4 on 2025-08-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0017_remove_playoffseries_seed1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="resumed_stats_count_until",
            field=models.IntegerField(
                blank=True,
                help_text="If the game was paused and resumed later, the time (in ticks from the start of the resumed game) to count stats until",
                null=True,
            ),
        ),
    ]
