# Generated by Django 4.2.23 on 2025-09-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0018_game_resumed_stats_count_until"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayerRegulationGameStats", new_name="PlayerRegulationStats",
        ),
        migrations.RenameModel(old_name="PlayerGameStats", new_name="PlayerStats",),
        migrations.RemoveField(model_name="playerweekstats", name="player_season",),
        migrations.DeleteModel(name="PlayerSeasonStats",),
        migrations.DeleteModel(name="PlayerWeekStats",),
    ]
