# Generated by Django 4.2.23 on 2025-09-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference",
            "0019_rename_playerregulationgamestats_playerregulationstats_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="had_ot",
            field=models.BooleanField(
                default=False, help_text="Whether this game went to overtime"
            ),
        ),
    ]
