# Generated by Django 4.2.23 on 2025-10-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0020_game_had_ot"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerregulationstats",
            name="dscar",
            field=models.FloatField(
                blank=True,
                help_text="Defensive Simple Caps Above Replacement",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="playerregulationstats",
            name="oscar",
            field=models.FloatField(
                blank=True,
                help_text="Offensive Simple Caps Above Replacement",
                null=True,
            ),
        ),
    ]
