# Generated by Django 4.2.23 on 2025-10-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0021_playerregulationstats_dscar_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="game", name="vod",),
        migrations.AddField(
            model_name="match",
            name="vod",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
