# Generated by Django 4.2.23 on 2025-10-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0022_remove_game_vod_match_vod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playergamelog",
            name="player_season",
            field=models.ForeignKey(
                db_column="player",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gamelogs",
                to="reference.playerseason",
            ),
        ),
    ]
