# Generated by Django 4.2.23 on 2025-12-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0023_alter_playergamelog_player_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardreceived",
            name="vote_share",
            field=models.FloatField(
                blank=True,
                help_text="Share of vote received (as decimal, not percent, so 20% is 0.2)",
                null=True,
            ),
        ),
    ]
