# Generated by Django 4.2.23 on 2025-12-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0024_awardreceived_vote_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardtype",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("player", "Player"),
                    ("captain", "Captain"),
                    ("team", "Team"),
                    ("unaffiliated", "Unaffiliated"),
                ],
                default="player",
                help_text="Type of award recipient",
                max_length=20,
            ),
        ),
    ]
