# Generated by Django 4.2.23 on 2026-03-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0027_legacy_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("prelim", "Prelim"),
                    ("add", "Add"),
                    ("drop", "Drop"),
                    ("trade for", "Trade For"),
                    ("trade away", "Trade Away"),
                ],
                max_length=10,
            ),
        ),
    ]
