# Generated by Django 5.2.4 on 2025-08-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="permission_tier",
            field=models.CharField(
                choices=[
                    ("full", "Full Data Editing"),
                    ("current", "Current Season Data Editing"),
                    ("entry", "New Data Entry Only"),
                    ("none", "No Editing"),
                ],
                default="entry",
                help_text="Permission level for data entry operations",
                max_length=10,
            ),
        ),
    ]
