# Generated by Django 4.2.23 on 2025-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="permission_tier",
            field=models.CharField(
                choices=[
                    ("full", "Full Data Editing"),
                    ("current", "Current Season Data Editing"),
                    ("entry", "New Data Entry Only"),
                    ("none", "No Editing"),
                ],
                default="none",
                help_text="Permission level for data entry operations",
                max_length=10,
            ),
        ),
    ]
